import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css';
import Navbar from '../components/navbar';
import Anuncios from '../pages/anuncios';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Cardano Sin Tecnicismos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>
        <h1 className="text-6xl font-bold">
          Aprende a usar Cardano jugando
        </h1>
        <button type="button" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mt-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">
          <Link href="https://canvas.instructure.com/enroll/MG9EFA" target="_blank">
          Regístrate
          </Link>
        </button>
      </main>
      <Anuncios />
    </div>
  )
}
